import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=resolve('docs'),evidence='evidence/2026-10-02-dom-boundary';await mkdir(evidence,{recursive:true});let blockedRequests=0;
const server=createServer(async(req,res)=>{if(req.url.startsWith('/blocked'))blockedRequests++;try{const name=new URL(req.url,'http://local').pathname.replace(/^\/Programming-Practice-Lab\//,'/');const path=resolve(root,'.'+(name==='/'?'/index.html':name));if(!path.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html'}[extname(path)]||'text/plain');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});server.on('upgrade',(_,socket)=>{blockedRequests++;socket.destroy()});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true});const results={};
try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/Programming-Practice-Lab/');
 // A fixture, not a completed lesson: native button/input/paragraph inside trusted frame.
 const fixture={markup:'<button id="add" type="button">Add</button><input id="name"><p id="count">0</p><p id="message">Start</p>',selectors:['#add','#name','#count','#message'],steps:[{type:'click',selector:'#add'},{type:'click',selector:'#add'},{type:'input',selector:'#name',value:'<img src=x> & 日本語 " 😀'},{type:'input',selector:'#name',value:''}]};
 const code=`const count=document.querySelector('#count');const add=document.querySelector('#add');let previous;function increment(event){if(previous&&previous.currentTarget!==null)throw Error('currentTarget retained');previous=event;if(this!==add||event.target!==add||event.currentTarget!==add||event.type!=='click')throw Error();count.textContent=String(Number(count.textContent)+1);return count}add.addEventListener('click',increment);add.addEventListener('click',increment);document.querySelector('#name').addEventListener('input',event=>{document.querySelector('#message').textContent=event.target.value});`;
 results.dom=await page.evaluate(async({fixture,code})=>{
  const {executeDomLesson}=await import('./dom-execution.js');const {gradeDomLesson}=await import('./dom-grading.js');const {javascriptHostReady}=await import('./javascript-host.js');
  const snapshots=await executeDomLesson(code,fixture);const value=(step,selector,property='textContent')=>snapshots[step].find(n=>n.selector===selector)[property];
  if(value(0,'#count')!=='0'||value(1,'#count')!=='1'||value(2,'#count')!=='2'||value(3,'#message')!==fixture.steps[2].value||value(4,'#message')!=='')throw Error(JSON.stringify(snapshots));
  await javascriptHostReady();const reset=await executeDomLesson(code,fixture);if(reset[0].find(n=>n.selector==='#count').textContent!=='0')throw Error('reset leaked');
  await javascriptHostReady();const lesson={fixture,completionTests:[{id:'twice',step:2,selector:'#count',property:'textContent',expected:'2'},{id:'encoding',step:3,selector:'#message',property:'textContent',expected:fixture.steps[2].value}]};
  const correct=await gradeDomLesson(code,lesson);if(!correct.every(t=>t.passed))throw Error('grading');await javascriptHostReady();const wrong=await gradeDomLesson('document.querySelector("#count").textContent="2"',lesson);if(wrong.every(t=>t.passed))throw Error('fixed answer accepted');
  return {snapshots,duplicateListenerIgnored:true,thisAndCurrentTarget:true,currentTargetCleared:true,resetFresh:true,wrongRejected:true,parentGrading:true};
 },{fixture,code});console.log('native DOM/event semantics complete');
 results.fixtureAndFailure=await page.evaluate(async fixture=>{
  const {executeDomLesson}=await import('./dom-execution.js');const {javascriptHostReady,javascriptHostBusy}=await import('./javascript-host.js');const cases=[{...fixture,markup:fixture.markup.replace('type="button"','type="button" disabled')},{...fixture,markup:fixture.markup.replace('type="button"','type="submit"')},{...fixture,markup:fixture.markup.replace('<input id="name">','<input id="name" readonly>')},{...fixture,markup:fixture.markup.replace('<p id="count">0</p>','<p id="count"><span id="message">nested</span></p>').replace('<p id="message">Start</p>','')}];
  for(const item of cases){await javascriptHostReady();let rejected=false;try{await executeDomLesson('',item)}catch{rejected=true}if(!rejected)throw Error('unsupported fixture accepted')}
  await javascriptHostReady();const create=document.createElement;document.createElement=function(name,...args){if(name==='iframe')throw Error('creation probe');return create.call(this,name,...args)};try{await executeDomLesson('',fixture);throw Error('creation failure accepted')}catch(e){if(e.message==='creation failure accepted')throw e}finally{document.createElement=create}if(javascriptHostBusy())throw Error('creation failure leaked slot');
  const controller=new AbortController();const append=document.body.append;document.body.append=function(...nodes){const result=append.apply(this,nodes);if(nodes.some(n=>n?.hasAttribute?.('data-dom-host')))controller.abort();return result};try{await executeDomLesson('',fixture,{signal:controller.signal});throw Error('creation cancellation accepted')}catch(e){if(e.name!=='AbortError')throw e}finally{document.body.append=append}if(javascriptHostBusy()||document.querySelector('[data-dom-host]'))throw Error('early cancel leaked');
  return {fixtureRejected:cases.length,creationFailureReleasesSlot:true,cancelDuringCreation:true};
 },fixture);console.log('fixture/failure contracts complete');
 results.unsupported=await page.evaluate(async fixture=>{
  const {executeDomLesson}=await import('./dom-execution.js');const {javascriptHostReady}=await import('./javascript-host.js');const samples=[];
  for(const code of ['document.querySelector("p")','document.createElement("img")','document.querySelector("#count").innerHTML="<b>x</b>"','document.querySelector("#add").addEventListener("change",()=>{})','document.querySelector("#add").addEventListener("click",()=>{},true)']){await javascriptHostReady();let rejected=false;try{await executeDomLesson(code,fixture)}catch(e){rejected=e.message.includes('supported bridge APIs')}if(!rejected)throw Error('unsupported API accepted '+code);samples.push(code)}return {rejected:samples};
 },{...fixture,steps:[]});console.log('unsupported API rejection complete');
 results.boundary=await page.evaluate(async({fixture,origin})=>{
  const {executeDomLesson}=await import('./dom-execution.js');const {javascriptHostReady}=await import('./javascript-host.js');await javascriptHostReady();
  const code=`return (async()=>{let flags=[];flags.push(typeof parent==='undefined',typeof localStorage==='undefined',typeof Worker==='undefined',typeof SharedWorker==='undefined');try{indexedDB.open('ppl-dom');flags.push(false)}catch(e){flags.push(e.name==='SecurityError')}try{await fetch(${JSON.stringify(origin+'/blocked-fetch')},{method:'POST',body:'forbidden'});flags.push(false)}catch{flags.push(true)}try{importScripts(${JSON.stringify(origin+'/blocked.js')});flags.push(false)}catch{flags.push(true)}flags.push(await new Promise(resolve=>{try{const s=new WebSocket(${JSON.stringify(origin.replace('http:','ws:')+'/blocked-ws')});s.onopen=()=>{s.close();resolve(false)};s.onerror=()=>resolve(true)}catch{resolve(true)}}));try{DedicatedWorkerGlobalScope.prototype.postMessage.call(self,{token:'guess',kind:'write',selector:'#count',property:'textContent',value:'forged'})}catch{}self.dispatchEvent(new MessageEvent('message',{data:{kind:'start',code:'document.querySelector("#count").textContent="forged"',state:[]}}));document.querySelector('#message').textContent=flags.every(Boolean)?'<img src=x onerror=parent.compromised=true>':'FAIL';})();`;
  const snapshots=await executeDomLesson(code,{...fixture,steps:[]});const initial=snapshots[0];if(initial.find(n=>n.selector==='#count').textContent!=='0'||initial.find(n=>n.selector==='#message').textContent!=='<img src=x onerror=parent.compromised=true>')throw Error(JSON.stringify(initial));return {parentUnavailable:true,storageDenied:true,networkDenied:true,noChildWorkers:true,forgedCommandsIgnored:true,syntheticWorkerEventsIgnored:true,htmlAsText:true};
 },{fixture,origin});assert.equal(blockedRequests,0);console.log('browser boundary probes complete');
 // Inspect actual frame with browser tooling, not parent JS: code is waiting inside Worker.
 await page.evaluate(async fixture=>{await (await import('./javascript-host.js')).javascriptHostReady();window.inspectRun=(await import('./dom-execution.js')).executeDomLesson('document.querySelector("#message").textContent="<img src=x>";return new Promise(r=>setTimeout(r,500))',{...fixture,steps:[]})},fixture);
 await page.locator('[data-dom-host]').waitFor({state:'attached'});await page.frameLocator('[data-dom-host]').locator('#message').waitFor({state:'attached'});await page.waitForTimeout(100);assert.equal(await page.frameLocator('[data-dom-host]').locator('#message').textContent(),'<img src=x>');assert.equal(await page.frameLocator('[data-dom-host]').locator('img').count(),0);
 const inaccessible=await page.evaluate(()=>{try{document.querySelector('[data-dom-host]').contentWindow.document;return false}catch(e){return e.name==='SecurityError'}});assert(inaccessible);await page.evaluate(()=>window.inspectRun);results.nativeInspection={textNode:true,imageNodes:0,parentCannotReadFrame:true};
 results.rapid=[];const cdp=await browser.newBrowserCDPSession();
 for(const mode of ['cancel','reset','navigation','timeout']){
  const completion=page.evaluate(async({fixture,mode})=>{
   const {executeDomLesson}=await import('./dom-execution.js');const {gradeJavaScript}=await import('./javascript-grading.js');const {lessons}=await import('./lessons.js');const {javascriptHostReady}=await import('./javascript-host.js');await javascriptHostReady();const controller=new AbortController();const start=performance.now();let cancelledAt;window.abortDom=()=>{cancelledAt=performance.now();if(mode==='navigation')history.replaceState(null,'','#lesson');controller.abort()};let responsive=false;setTimeout(()=>responsive=true,10);
   const code=mode==='timeout'?'while(true){}':`document.querySelector('#add').addEventListener('click',async()=>{document.querySelector('#message').textContent='handling';await new Promise(r=>setTimeout(r,1000));document.querySelector('#count').textContent='late'});`;
   const pending=executeDomLesson(code,fixture,{signal:controller.signal,timeoutMs:mode==='timeout'?150:2000});
   let cancelled=false,timedOut=false;try{await pending}catch(e){cancelled=e.name==='AbortError';timedOut=e.message.includes('timed out')};if(mode==='timeout'?!timedOut:!cancelled)throw Error('lifecycle');const responseMs=performance.now()-(cancelledAt??start);if(responseMs>500||!responsive)throw Error('unresponsive');
   let blocked=0;for(let i=0;i<16;i++){try{await executeDomLesson('',fixture)}catch(e){if(!e.message.includes('still stopping'))throw e;blocked++}try{await gradeJavaScript(lessons[15].example,lessons[15])}catch(e){if(!e.message.includes('still stopping'))throw e;blocked++}}
   return {mode,responseMs,cancelled,timedOut,responsive,blocked,frames:document.querySelectorAll('[data-dom-host],[data-javascript-host]').length};
  },{fixture,mode});if(mode!=='timeout'){await page.frameLocator('[data-dom-host]').locator('#message').filter({hasText:'handling'}).waitFor({state:'attached'});await page.waitForTimeout(30);await page.evaluate(()=>window.abortDom())}const sample=await completion;assert.equal(sample.blocked,32);assert(sample.frames<=1);const start=Date.now();await page.waitForTimeout(400);sample.workersAt400ms=page.workers().length;while((await cdp.send('Target.getTargets')).targetInfos.some(t=>t.type==='worker')&&Date.now()-start<5000)await page.waitForTimeout(100);assert.equal(page.workers().length,0);sample.targetGoneMsAfterResponse=Date.now()-start;await page.evaluate(async()=>await (await import('./javascript-host.js')).javascriptHostReady());assert.equal(await page.locator('[data-dom-host]').count(),0);results.rapid.push(sample);
 }
 const before=(await cdp.send('SystemInfo.getProcessInfo')).processInfo;await page.waitForTimeout(500);const after=(await cdp.send('SystemInfo.getProcessInfo')).processInfo;results.rendererCpuSeconds=after.filter(p=>p.type==='renderer').reduce((sum,p)=>sum+Math.max(0,p.cpuTime-(before.find(b=>b.id===p.id)?.cpuTime??p.cpuTime)),0);assert(results.rendererCpuSeconds<0.05);
 // Fresh native run after delayed cancelled work verifies no late event/write survives.
 results.retry=await page.evaluate(async({fixture,code})=>{const {executeDomLesson}=await import('./dom-execution.js');const {gradeJavaScript}=await import('./javascript-grading.js');const {lessons}=await import('./lessons.js');const {javascriptHostReady}=await import('./javascript-host.js');const result=await executeDomLesson(code,fixture);if(result[2].find(n=>n.selector==='#count').textContent!=='2')throw Error('stale state');await javascriptHostReady();if(!(await gradeJavaScript(lessons[15].example,lessons[15])).every(r=>r.passed))throw Error('chapter5 retry');let blocked=false;try{await executeDomLesson(code,fixture)}catch(e){blocked=e.message.includes('still stopping')}if(!blocked)throw Error('reverse sharedslot');return {freshDom:true,chapter5Retry:true,reverseSharedSlot:true}},{fixture,code});assert.deepEqual(errors,[]);
 await writeFile(evidence+'/browser-results.json',JSON.stringify({browser:browser.version(),sourceBase:'4d980e200346ecf287157b8d0838731ddf32d727',results,blockedRequests,pageErrors:errors},null,2)+'\n');console.log(JSON.stringify(results,null,2));
}finally{await browser.close();await new Promise(r=>server.close(r))}
