import {execFileSync} from 'node:child_process';
import {createServer} from 'node:http';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {chromium} from '../test-tools/node_modules/playwright/index.mjs';
const sha=process.env.REVIEW_SHA||'2e50c53c666a5d44cdfa8a4e5715f3270e7cb616',output=resolve('../lesson-review'),files=new Map();
for(const p of execFileSync('git',['ls-tree','-r','--name-only',sha,'docs'],{encoding:'utf8'}).trim().split('\n'))files.set('/'+p.slice(5),execFileSync('git',['show',sha+':'+p],{maxBuffer:8*1024*1024}));
const server=createServer((q,r)=>{let p=new URL(q.url,'http://local').pathname;if(p==='/')p='/index.html';const file=files.get(p);if(!file){r.writeHead(404);r.end();return;}r.setHeader('Content-Type',{'.js':'text/javascript','.html':'text/html','.css':'text/css'}[extname(p)]||'application/octet-stream');r.end(file);});
await new Promise(d=>server.listen(0,'127.0.0.1',d));let browser;
const evidence={sha,immutableGitServing:true,width:375,observations:[],errors:[],external:[]};await mkdir(output,{recursive:true});
try{
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:375,height:900},reducedMotion:'reduce'});const origin='http://127.0.0.1:'+server.address().port;
 page.on('pageerror',e=>evidence.errors.push(e.message));await page.route('**/*',route=>{const u=route.request().url();if(u.startsWith(origin)||u.startsWith('data:'))return route.continue();evidence.external.push(u);return route.abort();});await page.goto(origin);
 const catalog=await page.evaluate(async()=>{const {lessonCatalog,lessons}=await import('./lessons.js');const{toLegacyLesson}=await import('./lesson-format.js');return{count:lessonCatalog.length,frozen:Object.isFrozen(lessonCatalog)&&lessonCatalog.every(l=>Object.isFrozen(l.exercise.completionTests)),versions:lessonCatalog.every(l=>l.version===1),legacyViews:JSON.stringify(lessonCatalog.map(toLegacyLesson))===JSON.stringify(lessons)};});assert.deepEqual(catalog,{count:21,frozen:true,versions:true,legacyViews:true});evidence.observations.push({catalog});
 const seed=await page.evaluate(async()=>{const{lessons}=await import('./lessons.js');const l=lessons.find(l=>l.id==='css01'),record={code:l.example+'\n/* learner unfinished */',checkedCode:l.example,attempts:5,completed:true,result:l.completionTests.map(t=>({id:t.id,passed:true}))};localStorage.setItem('ppl.foundation.progress.v1',JSON.stringify({version:1,lessonId:l.id,view:'practice',lessons:{[l.id]:record}}));localStorage.setItem('ppl.profile.v1.topic','css');localStorage.setItem('unrelated','keep');history.replaceState(null,'','#practice');return{record,example:l.example};});
 await page.reload();const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ppl.foundation.progress.v1')).lessons.css01);assert.deepEqual(await read(),seed.record);assert.equal(await page.locator('#result-status').textContent(),'未確認');assert.equal(await page.locator('#editor').inputValue(),seed.record.code);evidence.observations.push({legacySavedCodeHistory:true,staleResultHidden:true});
 await page.locator('#editor').fill(seed.example);await page.locator('#check-code').click();await page.getByText('演習を完了しました',{exact:true}).waitFor();assert.equal((await read()).attempts,6);
 await page.evaluate(()=>{window.reviewDeliveries=[];const Native=window.MessageChannel;window.MessageChannel=function(){const ch=new Native(),p=ch.port1,d=Object.getOwnPropertyDescriptor(MessagePort.prototype,'onmessage');let fn;Object.defineProperty(p,'onmessage',{get(){return fn},set(f){fn=f;d.set.call(p,e=>window.reviewDeliveries.push(()=>f(e)));}});return ch;};});
 await page.locator('#check-code').click();await page.waitForFunction(()=>window.reviewDeliveries.length===1);await page.locator('#editor').fill(seed.example+'\n/*cancel*/');await page.locator('#editor').fill(seed.example);await page.locator('#check-code').click();await page.waitForFunction(()=>window.reviewDeliveries.length===2);await page.evaluate(()=>window.reviewDeliveries.shift()());assert.equal((await read()).attempts,6);assert.equal(await page.locator('#check-code').isDisabled(),true);await page.evaluate(()=>window.reviewDeliveries.shift()());await page.getByText('演習を完了しました',{exact:true}).waitFor();assert.equal((await read()).attempts,7);evidence.observations.push({sameCodeCancelledOldResultRefused:true,currentRetryAccepted:true});
 await page.reload();const persisted=await page.evaluate(()=>localStorage.getItem('ppl.foundation.progress.v1'));await page.evaluate(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ppl.foundation.progress.v1')throw new DOMException('quota','QuotaExceededError');return set.call(this,k,v);};});await page.locator('#editor').fill(seed.example+'\n/*unsaved learner*/');assert.equal(await page.locator('#save-status').textContent(),'保存できません。この画面内のみ保持します');assert.equal(await page.evaluate(()=>localStorage.getItem('ppl.foundation.progress.v1')),persisted);await page.reload();assert.equal(await page.locator('#editor').inputValue(),seed.example);assert.equal((await read()).attempts,7);evidence.observations.push({quotaRefusalKeptStoredBytes:true,reloadRestoredPriorCode:true});
 const store=await page.evaluate(()=>{const state=JSON.parse(localStorage.getItem('ppl.foundation.progress.v1'));return{version:state.version,noEnvelope:Object.values(state.lessons).every(r=>!('exercise'in r)&&!('runId'in r)&&!('schemaVersion'in r)),nativeKey:localStorage.getItem('ppl.profile.v1.topic'),unrelated:localStorage.getItem('unrelated'),horizontalOverflow:document.documentElement.scrollWidth>innerWidth};});assert.deepEqual(store,{version:1,noEnvelope:true,nativeKey:'css',unrelated:'keep',horizontalOverflow:false});evidence.observations.push({store});assert.deepEqual(evidence.errors,[]);assert.deepEqual(evidence.external,[]);await page.screenshot({path:resolve(output,`mobile-common-progress-${sha.slice(0,7)}.png`),fullPage:true});evidence.pass=true;console.log(JSON.stringify(evidence));
}catch(e){evidence.pass=false;evidence.failure={name:e.name,message:e.message};console.log(JSON.stringify(evidence));throw e;}
finally{await writeFile(resolve(output,`mobile-common-progress-${sha.slice(0,7)}.json`),JSON.stringify(evidence,null,2));await browser?.close();await new Promise(d=>server.close(d));}
