import {execFileSync} from 'node:child_process';import {createServer} from 'node:http';import {mkdir,writeFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';import {chromium} from '../test-tools/node_modules/playwright/index.mjs';
const sha='382def60674d07900f944b72e5b515ff25200acc',root=resolve('../db-review'),files=new Map();for(const p of execFileSync('git',['ls-tree','-r','--name-only',sha,'docs'],{encoding:'utf8'}).trim().split('\n'))files.set('/'+p.slice(5),execFileSync('git',['show',sha+':'+p]));
const server=createServer((q,r)=>{let p=new URL(q.url,'http://local').pathname;if(p==='/')p='/index.html';const v=files.get(p);if(!v){r.writeHead(404);r.end();return;}r.setHeader('Content-Type',{'.js':'text/javascript','.html':'text/html','.css':'text/css'}[extname(p)]||'application/octet-stream');r.end(v);});await new Promise(d=>server.listen(0,'127.0.0.1',d));await mkdir(root,{recursive:true});const browser=await chromium.launch({headless:true});const report={sha,immutableGitServing:true,width:375,states:[],errors:[]};
try{
 for(const error of [false,true]){
  const ctx=await browser.newContext({viewport:{width:375,height:900},reducedMotion:'reduce'});await ctx.addInitScript(error=>{if(top!==window)return;localStorage.setItem('ppl.foundation.progress.v1',JSON.stringify({version:1,lessonId:'html03',view:'practice',lessons:{html03:{code:'<h1>legacy draft</h1>',checkedCode:'earlier code',attempts:9,completed:true,result:null}}}));window.layoutHold=false;window.layoutAck=[];const d=Object.getOwnPropertyDescriptor(IDBTransaction.prototype,'oncomplete');Object.defineProperty(IDBTransaction.prototype,'oncomplete',{get:d.get,set(fn){d.set.call(this,function(e){if(window.layoutHold&&this.db.name==='ppl.foundation.progress')window.layoutAck.push(()=>fn.call(this,e));else fn.call(this,e);});}});if(error){const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.transaction.db.name==='ppl.foundation.progress')throw new DOMException('synthetic quota','QuotaExceededError');return put.apply(this,args);};}},error);
  const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port+'/#practice');await p.waitForFunction(()=>['saved','error'].includes(document.querySelector('#save-status')?.dataset.state));
  async function inspect(state){await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));const v=await p.locator('.practice-head').evaluate(head=>{const b=head.querySelector('button'),s=head.querySelector('#save-status'),h=head.querySelector('h1');const rect=n=>{const r=n.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height};};return{state:s.dataset.state,text:s.textContent,back:rect(b),status:rect(s),title:rect(h),backWhiteSpace:getComputedStyle(b).whiteSpace,statusFont:getComputedStyle(s).fontSize,overflow:document.documentElement.scrollWidth>innerWidth,headerHeight:head.getBoundingClientRect().height};});assert.equal(v.state,state);assert.equal(v.overflow,false);assert.equal(v.backWhiteSpace,'nowrap');assert.ok(v.back.height<=50&&v.back.width>=100);assert.ok(v.status.left>=0&&v.status.right<=375);assert.ok(v.title.left>=0&&v.title.right<=375);if(state!=='saved'){assert.ok(v.status.top>=v.title.bottom);assert.ok(v.status.top>=v.back.bottom);assert.ok(v.status.width>=300);}if(state==='error')assert.match(v.text,/旧保存から復元しました/);assert.ok(parseFloat(v.statusFont)>=12);await p.screenshot({path:resolve(root,'layout-'+state+'-382def6.png')});report.states.push(v);}
  await inspect(error?'error':'saved');if(!error){await p.evaluate(()=>window.layoutHold=true);await p.locator('#editor').fill('<h1>pending learner draft</h1>');await p.waitForFunction(()=>window.layoutAck.length===1);await inspect('pending');await p.evaluate(()=>{window.layoutHold=false;window.layoutAck.shift()();});await p.waitForFunction(()=>document.querySelector('#save-status').dataset.state==='saved');}
  await ctx.close();
 }
 assert.deepEqual(report.errors,[]);report.pass=true;console.log(JSON.stringify(report,null,2));
}catch(e){report.pass=false;report.failure=e.message;throw e;}finally{await writeFile(resolve(root,'layout-382def6.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(d=>server.close(d));}
