import {execFileSync} from 'node:child_process';
import {createServer} from 'node:http';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {chromium} from '../test-tools/node_modules/playwright/index.mjs';
const sha=process.env.REVIEW_SHA||'de6bc0e7be4394190d8a774398445dae55582ad7',output=resolve('../db-review'),files=new Map();
for(const p of execFileSync('git',['ls-tree','-r','--name-only',sha,'docs'],{encoding:'utf8'}).trim().split('\n'))files.set('/'+p.slice(5),execFileSync('git',['show',sha+':'+p],{maxBuffer:8*1024*1024}));
const server=createServer((q,r)=>{let p=new URL(q.url,'http://local').pathname;if(p==='/')p='/index.html';const bytes=files.get(p);if(!bytes){r.writeHead(404);r.end();return;}r.setHeader('Content-Type',{'.js':'text/javascript','.html':'text/html','.css':'text/css'}[extname(p)]||'application/octet-stream');r.end(bytes);});await new Promise(d=>server.listen(0,'127.0.0.1',d));let browser;const origin='http://127.0.0.1:'+server.address().port;
const evidence={sha,immutableGitServing:true,width:375,observations:[],errors:[],external:[]};await mkdir(output,{recursive:true});
try{
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:375,height:900},reducedMotion:'reduce'});
 await context.addInitScript(()=>{
  if(window.top!==window)return;
  if(!localStorage.getItem('reviewSeed')){localStorage.setItem('reviewSeed','1');localStorage.setItem('ppl.foundation.progress.v1',JSON.stringify({version:1,lessonId:'css01',view:'practice',lessons:{css01:{code:'/* old learner draft */',checkedCode:'old checked code',result:null,attempts:8,completed:true},js04:{code:'unexecuted DOM draft',checkedCode:null,result:null,attempts:6,completed:true}}}));localStorage.setItem('ppl.profile.v1.topic','css');localStorage.setItem('unrelated','keep');}
  window.reviewHold=false;window.reviewAcks=[];window.reviewAbort=false;
  const complete=Object.getOwnPropertyDescriptor(IDBTransaction.prototype,'oncomplete');Object.defineProperty(IDBTransaction.prototype,'oncomplete',{get:complete.get,set(fn){complete.set.call(this,function(e){if(this.db.name==='ppl.foundation.progress'&&this.mode==='readwrite'&&window.reviewHold)window.reviewAcks.push(()=>fn.call(this,e));else fn.call(this,e);});}});
  const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){const request=put.apply(this,args);if(window.reviewAbort&&this.transaction.db.name==='ppl.foundation.progress')request.addEventListener('success',()=>this.transaction.abort());return request;};
 });
 async function newPage(){const p=await context.newPage();p.on('pageerror',e=>evidence.errors.push(e.message));await p.route('**/*',r=>{if(r.request().url().startsWith(origin)||r.request().url().startsWith('data:'))return r.continue();evidence.external.push(r.request().url());return r.abort();});await p.goto(origin+'/#practice');return p;}
 const saved=p=>p.waitForFunction(()=>document.querySelector('#save-status')?.dataset.state==='saved');const failed=p=>p.waitForFunction(()=>document.querySelector('#save-status')?.dataset.state==='error');
 const record=p=>p.evaluate(()=>new Promise((done,bad)=>{const q=indexedDB.open('ppl.foundation.progress',1);q.onerror=()=>bad(q.error);q.onsuccess=()=>{const db=q.result;db.onversionchange=()=>db.close();const tx=db.transaction('records'),r=tx.objectStore('records').get('foundation');tx.oncomplete=()=>{db.close();done(r.result);};tx.onabort=()=>{db.close();bad(tx.error);};};}));
 const raw=p=>p.evaluate(()=>({legacy:localStorage.getItem('ppl.foundation.progress.v1'),topic:localStorage.getItem('ppl.profile.v1.topic'),unrelated:localStorage.getItem('unrelated')}));
 const p=await newPage();await saved(p);const legacy=await raw(p),initial=await record(p);assert.equal(initial.revision,1);assert.equal(initial.state.lessons.css01.code,'/* old learner draft */');assert.equal(initial.state.lessons.css01.checkedCode,'old checked code');assert.equal(initial.state.lessons.css01.attempts,8);assert.equal(initial.state.lessons.css01.completed,true);assert.equal(initial.state.lessons.js04.attempts,6);assert.equal(await p.locator('#result-status').textContent(),'未確認');evidence.observations.push({migration:true,legacyHistory:true,staleResultHidden:true});
 await p.locator('#editor').fill('/* committed draft */');await saved(p);const committed=await record(p);assert.ok(committed.revision>initial.revision);assert.deepEqual(await raw(p),legacy);await p.reload();await saved(p);assert.equal(await p.locator('#editor').inputValue(),'/* committed draft */');assert.deepEqual(await record(p),committed);evidence.observations.push({reloadUsesDB:true,legacyRawUnchanged:true});
 await p.evaluate(()=>window.reviewHold=true);await p.locator('#editor').fill('/* old delayed acknowledgement */');await p.waitForFunction(()=>window.reviewAcks.length===1);assert.equal(await p.locator('#save-status').getAttribute('data-state'),'pending');await p.locator('#editor').fill('/* latest queued snapshot */');await p.evaluate(()=>window.reviewAcks.shift()());await p.waitForFunction(()=>window.reviewAcks.length===1);assert.equal(await p.locator('#save-status').getAttribute('data-state'),'pending');assert.equal((await record(p)).state.lessons.css01.code,'/* latest queued snapshot */');await p.evaluate(()=>{window.reviewHold=false;window.reviewAcks.shift()();});await saved(p);evidence.observations.push({commitAcknowledgementRequired:true,staleAckDoesNotMarkLatestSaved:true,latestQueueCommitted:true});
 const beforeAbort=await record(p);await p.evaluate(()=>window.reviewAbort=true);await p.locator('#editor').fill('/* abort after native put success */');await failed(p);assert.deepEqual(await record(p),beforeAbort);assert.equal(await p.locator('#editor').inputValue(),'/* abort after native put success */');assert.deepEqual(await raw(p),legacy);await p.evaluate(()=>window.reviewAbort=false);await p.locator('#editor').fill('/* retry saved */');await saved(p);assert.equal((await record(p)).state.lessons.css01.code,'/* retry saved */');evidence.observations.push({nativeTransactionAbortKeepsDB:true,errorRetainsEditor:true,retrySaved:true});
 const second=await newPage();await saved(second);await p.locator('#editor').fill('/* winner tab */');await saved(p);const winner=await record(p);await second.locator('#editor').fill('/* stale tab draft */');await failed(second);assert.match(await second.locator('#save-status').textContent(),/別の画面/);assert.deepEqual(await record(p),winner);assert.equal(await second.locator('#editor').inputValue(),'/* stale tab draft */');await second.reload();await saved(second);assert.equal(await second.locator('#editor').inputValue(),'/* winner tab */');evidence.observations.push({nativeTwoTabConflictPreservesWinner:true,conflictRetainsDraft:true,conflictReloadUsesWinner:true});await second.close();
 await p.evaluate(()=>window.reviewHold=true);await p.locator('#editor').fill('/* committed before hide with held ack */');await p.waitForFunction(()=>window.reviewAcks.length===1);await p.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide'));window.reviewHold=false;window.reviewAcks.shift()();});await failed(p);await p.reload();await saved(p);assert.equal(await p.locator('#editor').inputValue(),'/* committed before hide with held ack */');evidence.observations.push({pagehideIgnoresStaleAck:true,reloadReadsActualCommit:true});assert.deepEqual(await raw(p),legacy);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:resolve(output,'mobile-'+sha.slice(0,7)+'.png'),fullPage:true});
 await context.close();
 // Separate disposable context: hold the initial migration completion callback.
 const boot=await browser.newContext({viewport:{width:375,height:900}});await boot.addInitScript(()=>{if(window.top!==window)return;window.bootstrapAcks=[];const d=Object.getOwnPropertyDescriptor(IDBTransaction.prototype,'oncomplete');Object.defineProperty(IDBTransaction.prototype,'oncomplete',{get:d.get,set(fn){d.set.call(this,function(e){if(this.db.name==='ppl.foundation.progress'&&this.mode==='readwrite')window.bootstrapAcks.push(()=>fn.call(this,e));else fn.call(this,e);});}});});const bp=await boot.newPage();await bp.goto(origin+'/#home',{waitUntil:'commit'});await bp.waitForFunction(()=>window.bootstrapAcks?.length===1);assert.equal(await bp.locator('#editor').isDisabled(),true);await bp.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide'));window.bootstrapAcks.shift()();});await bp.waitForTimeout(100);const bootState=await bp.locator('#save-status').getAttribute('data-state'),bootDisabled=await bp.locator('#editor').isDisabled();assert.equal(bootDisabled,true);assert.notEqual(bootState,'saved');assert.equal(await bp.locator('#practice-title').textContent(),'HTMLの基本構造を入力する');evidence.observations.push({initialRestoreHideSynthetic:true,statusAfterHeldInitialAck:bootState,editorStillDisabled:bootDisabled,noLateUIBoot:true});await boot.close();
 const pre=await browser.newContext(),pp=await pre.newPage();await pp.goto(origin+'/project-preview.html');const preAbort=await pp.evaluate(async()=>{const {openProgressDatabase,createIndexedProgressRepository}=await import('./indexed-progress.js'),{lessons}=await import('./lessons.js');let calls=0;const controller=new AbortController();controller.abort();let driverError;try{await openProgressDatabase(()=>{calls++;return indexedDB;},{lessons,signal:controller.signal});}catch(e){driverError=e.name;}const repo=await createIndexedProgressRepository(()=>localStorage,lessons,()=>{calls++;return indexedDB;},{signal:controller.signal});const save=await repo.save();repo.close();return{calls,driverError,status:repo.status.phase,save,databases:(await indexedDB.databases()).map(d=>d.name)};});assert.deepEqual(preAbort,{calls:0,driverError:'AbortError',status:'error',save:false,databases:[]});evidence.observations.push({preAbortedOpenAndRepository:preAbort});
 const lateOpen=await pp.evaluate(async()=>{const {openProgressDatabase}=await import('./indexed-progress.js'),{lessons}=await import('./lessons.js');const controller=new AbortController();let release,heldReady;const ready=new Promise(r=>heldReady=r);const factory={open(name,version){const q=indexedDB.open(name,version),d=Object.getOwnPropertyDescriptor(IDBRequest.prototype,'onsuccess');Object.defineProperty(q,'onsuccess',{set(fn){d.set.call(q,e=>{release=()=>fn(e);heldReady();});}});return q;}};const opening=openProgressDatabase(()=>factory,{lessons,signal:controller.signal});await ready;controller.abort();let error;try{await opening;}catch(e){error=e.name;}release();const upgrade=await new Promise((done,bad)=>{const q=indexedDB.open('ppl.foundation.progress',2);const timer=setTimeout(()=>bad(Error('late open leaked connection')),1000);q.onerror=()=>bad(q.error);q.onsuccess=()=>{clearTimeout(timer);q.result.close();done(true);};});return{error,lateConnectionClosed:upgrade};});assert.deepEqual(lateOpen,{error:'AbortError',lateConnectionClosed:true});evidence.observations.push({abortedNativeOpenLateSuccess:lateOpen});await pre.close();
 assert.deepEqual(evidence.errors,[]);assert.deepEqual(evidence.external,[]);evidence.pass=true;console.log(JSON.stringify(evidence,null,2));
}catch(e){evidence.pass=false;evidence.failure={name:e.name,message:e.message};console.log(JSON.stringify(evidence,null,2));throw e;}
finally{await writeFile(resolve(output,'results-'+sha.slice(0,7)+'.json'),JSON.stringify(evidence,null,2));await browser?.close();await new Promise(d=>server.close(d));}
