import {execFileSync} from 'node:child_process';import {createServer} from 'node:http';import {mkdir,writeFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';import {chromium} from '../test-tools/node_modules/playwright/index.mjs';
const sha='7acb4e424f9554e052a512cf3bbf76c73db17ba9',output=resolve('../db-review'),files=new Map();for(const p of execFileSync('git',['ls-tree','-r','--name-only',sha,'docs'],{encoding:'utf8'}).trim().split('\n'))files.set('/'+p.slice(5),execFileSync('git',['show',sha+':'+p]));const server=createServer((q,r)=>{let p=new URL(q.url,'http://local').pathname;if(p==='/')p='/index.html';const b=files.get(p);if(!b){r.writeHead(404);r.end();return;}r.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html'}[extname(p)]||'application/octet-stream');r.end(b);});await new Promise(d=>server.listen(0,'127.0.0.1',d));await mkdir(output,{recursive:true});const browser=await chromium.launch({headless:true}),report={sha,immutableGitServing:true,width:375,cases:[],errors:[]};
try{
 for(const kind of ['cycle','bigint','valid-json']){
  const ctx=await browser.newContext({viewport:{width:375,height:900},reducedMotion:'reduce'});await ctx.addInitScript(()=>{if(window.top!==window)return;if(!localStorage.getItem('corruptionSeed')){localStorage.setItem('corruptionSeed','1');localStorage.setItem('ppl.foundation.progress.v1',JSON.stringify({version:1,lessonId:'html03',view:'practice',lessons:{html03:{code:'<h1>old legacy code</h1>',checkedCode:'legacy checked code',attempts:12,completed:true,result:null}}}));localStorage.setItem('unrelated','keep');localStorage.setItem('ppl.profile.v1.topic','css');}});const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port+'/#practice');await p.waitForFunction(()=>document.querySelector('#save-status')?.dataset.state==='saved');const raw=await p.evaluate(()=>localStorage.getItem('ppl.foundation.progress.v1'));
  const seeded=await p.evaluate(async kind=>{const{lessons}=await import('./lessons.js');const l=lessons.find(l=>l.id==='html03');return new Promise((done,bad)=>{const q=indexedDB.open('ppl.foundation.progress',1);q.onerror=()=>bad(q.error);q.onsuccess=()=>{const db=q.result;db.onversionchange=()=>db.close();const tx=db.transaction('records','readwrite'),store=tx.objectStore('records'),r=store.get('foundation');let revision;r.onsuccess=()=>{const v=r.result;revision=v.revision;let actual;if(kind==='cycle'){actual={};actual.self=actual;}else actual=kind==='bigint'?42n:'valid plain string';v.state.lessons.html03.code='<h1>'+kind+' DB marker</h1>';v.state.lessons.html03.checkedCode=v.state.lessons.html03.code;v.state.lessons.html03.result=l.completionTests.map(t=>({id:t.id,passed:true,actual,expected:'expected string'}));store.put(v,'foundation');};tx.oncomplete=()=>{db.close();done({revision,ids:l.completionTests.map(t=>t.id)});};tx.onabort=()=>{db.close();bad(tx.error);};};});},kind);
  async function retained(){return p.evaluate(()=>new Promise((done,bad)=>{const q=indexedDB.open('ppl.foundation.progress',1);q.onerror=()=>bad(q.error);q.onsuccess=()=>{const db=q.result;db.onversionchange=()=>db.close();const tx=db.transaction('records'),r=tx.objectStore('records').get('foundation');tx.oncomplete=()=>{const v=r.result,e=v.state.lessons.html03,a=e.result?.[0].actual;db.close();done({revision:v.revision,code:e.code,ids:e.result?.map(t=>t.id),cyclic:a?.self===a,bigint:typeof a==='bigint',actualString:typeof a==='bigint'?String(a):typeof a==='string'?a:null,attempts:e.attempts,completed:e.completed});};tx.onabort=()=>{db.close();bad(tx.error);};};}));}
  await p.evaluate(()=>{window.corruptionPuts=0;const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.transaction.db.name==='ppl.foundation.progress')window.corruptionPuts++;return put.apply(this,args);};});
  if(kind!=='valid-json'){
   await p.locator('#editor').fill('<h1>unsaved replacement draft</h1>');await p.waitForFunction(()=>document.querySelector('#save-status').dataset.state==='error');assert.match(await p.locator('#save-status').textContent(),/読み取れません/);assert.equal(await p.evaluate(()=>window.corruptionPuts),0);const before=await retained();assert.equal(before.revision,seeded.revision);assert.equal(before.code,'<h1>'+kind+' DB marker</h1>');assert.deepEqual(before.ids,seeded.ids);assert.equal(kind==='cycle'?before.cyclic:before.bigint,true);await p.reload();await p.waitForFunction(()=>document.querySelector('#save-status')?.dataset.state==='error');assert.equal(await p.locator('#editor').inputValue(),'<h1>old legacy code</h1>');assert.match(await p.locator('#save-status').textContent(),/旧保存から復元しました.*読み取れません/);assert.match(await p.locator('#attempts').textContent(),/12回.*完了履歴あり/);await p.locator('#editor').fill('<h1>memory only draft</h1>');assert.deepEqual(await retained(),before);assert.equal(await p.evaluate(()=>localStorage.getItem('ppl.foundation.progress.v1')),raw);assert.equal(await p.evaluate(()=>localStorage.getItem('unrelated')),'keep');assert.equal(await p.evaluate(()=>localStorage.getItem('ppl.profile.v1.topic')),'css');report.cases.push({kind,matchingIDs:true,nativeStructuredClone:true,saveRefusedBeforePut:true,recordRetainedBeforeAndAfterReload:true,legacyFallbackCodeHistoryTruthful:true,legacyRawUnchanged:true});
  }else{
   await p.reload();await p.waitForFunction(()=>document.querySelector('#save-status')?.dataset.state==='saved');assert.equal(await p.locator('#editor').inputValue(),'<h1>valid-json DB marker</h1>');assert.equal(await p.locator('#result-title').textContent(),'演習を完了しました');const before=await retained();assert.equal(before.actualString,'valid plain string');assert.equal(before.attempts,12);assert.equal(before.completed,true);await p.locator('#editor').fill('<h1>valid new code</h1>');await p.waitForFunction(()=>document.querySelector('#save-status').dataset.state==='saved');assert.ok((await retained()).revision>before.revision);assert.equal(await p.evaluate(()=>localStorage.getItem('ppl.foundation.progress.v1')),raw);report.cases.push({kind,DBCodeAndResultsAdopted:true,validJSONHistoryPreserved:true,nextSaveCommitted:true,legacyRawUnchanged:true});
  }
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(kind==='cycle'){await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:resolve(output,'cyclic-fallback-7acb4e4.png')});}await ctx.close();
 }
 assert.deepEqual(report.errors,[]);report.pass=true;console.log(JSON.stringify(report,null,2));
}catch(e){report.pass=false;report.failure=e.message;throw e;}finally{await writeFile(resolve(output,'cyclic-review-7ac.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(d=>server.close(d));}
